import type { Locale } from "./config";

export type PortalCopy = {
  auth: {
    login: string; email: string; password: string; forgot: string; signIn: string;
    signingIn: string; invalid: string; resetTitle: string; resetIntro: string;
    sendReset: string; resetSent: string; newPassword: string; savePassword: string;
    passwordSaved: string; passwordTooShort: string; resetLinkInvalid: string;
    passwordUpdateFailed: string; logout: string;
  };
  nav: {
    overview: string; assessments: string; properties: string; subscriptions: string;
    invoices: string; payments: string; profile: string; support: string;
  };
  dashboard: {
    title: string; welcome: string; accountStatus: string; property: string;
    subscription: string; nextPayment: string; balance: string; latestInvoice: string;
    upcomingService: string; activity: string; empty: string; download: string;
    reference: string; submitted: string; status: string; address: string; frequency: string;
    amount: string; date: string; due: string; paid: string; contactSupport: string;
    access: string; services: string; acceptProposal: string; save: string; saved: string; subject: string; message: string;
  };
};

const en: PortalCopy = {
  auth: { login:"Login",email:"Email address",password:"Password",forgot:"Forgot password?",signIn:"Sign in",signingIn:"Signing in…",invalid:"The email or password is incorrect.",resetTitle:"Reset your password",resetIntro:"Enter your email and we will send secure reset instructions.",sendReset:"Send reset link",resetSent:"If an account exists, reset instructions have been sent.",newPassword:"New password",savePassword:"Save new password",passwordSaved:"Your password has been updated.",passwordTooShort:"Use at least 12 characters.",resetLinkInvalid:"This reset link is invalid or expired. Request a new one.",passwordUpdateFailed:"The password could not be updated. Please try again.",logout:"Log out" },
  nav: { overview:"Overview",assessments:"Assessments",properties:"Properties",subscriptions:"Subscriptions",invoices:"Invoices",payments:"Payments",profile:"Profile",support:"Support" },
  dashboard: { title:"My Account",welcome:"Welcome back",accountStatus:"Account status",property:"Property",subscription:"Subscription",nextPayment:"Next payment",balance:"Outstanding balance",latestInvoice:"Latest invoice",upcomingService:"Upcoming service",activity:"Recent activity",empty:"Nothing to show yet.",download:"Download",reference:"Reference",submitted:"Submitted",status:"Status",address:"Address",frequency:"Frequency",amount:"Amount",date:"Date",due:"Due",paid:"Paid",contactSupport:"Contact support",access:"Access",services:"Services",acceptProposal:"Accept proposal and continue to secure payment",save:"Save",saved:"Saved",subject:"Subject",message:"Message" },
};

export const portalCopy: Record<Locale, PortalCopy> = {
  en,
  nl: { auth:{login:"Inloggen",email:"E-mailadres",password:"Wachtwoord",forgot:"Wachtwoord vergeten?",signIn:"Inloggen",signingIn:"Bezig met inloggen…",invalid:"Het e-mailadres of wachtwoord is onjuist.",resetTitle:"Wachtwoord herstellen",resetIntro:"Vul uw e-mailadres in voor veilige herstelinstructies.",sendReset:"Herstellink versturen",resetSent:"Als het account bestaat, zijn instructies verstuurd.",newPassword:"Nieuw wachtwoord",savePassword:"Nieuw wachtwoord opslaan",passwordSaved:"Uw wachtwoord is bijgewerkt.",passwordTooShort:"Gebruik minimaal 12 tekens.",resetLinkInvalid:"Deze herstellink is ongeldig of verlopen. Vraag een nieuwe aan.",passwordUpdateFailed:"Het wachtwoord kon niet worden bijgewerkt. Probeer het opnieuw.",logout:"Uitloggen"}, nav:{overview:"Overzicht",assessments:"Beoordelingen",properties:"Woningen",subscriptions:"Abonnementen",invoices:"Facturen",payments:"Betalingen",profile:"Profiel",support:"Ondersteuning"}, dashboard:{...en.dashboard,title:"Mijn account",welcome:"Welkom terug",accountStatus:"Accountstatus",property:"Woning",subscription:"Abonnement",nextPayment:"Volgende betaling",balance:"Openstaand saldo",latestInvoice:"Laatste factuur",upcomingService:"Volgende service",activity:"Recente activiteit",empty:"Nog niets om te tonen.",download:"Downloaden",reference:"Referentie",submitted:"Ingediend",status:"Status",address:"Adres",frequency:"Frequentie",amount:"Bedrag",date:"Datum",due:"Vervaldatum",paid:"Betaald",contactSupport:"Contact opnemen"} },
  fr: { auth:{login:"Connexion",email:"Adresse e-mail",password:"Mot de passe",forgot:"Mot de passe oublié ?",signIn:"Se connecter",signingIn:"Connexion…",invalid:"L’adresse e-mail ou le mot de passe est incorrect.",resetTitle:"Réinitialiser le mot de passe",resetIntro:"Saisissez votre e-mail pour recevoir des instructions sécurisées.",sendReset:"Envoyer le lien",resetSent:"Si le compte existe, les instructions ont été envoyées.",newPassword:"Nouveau mot de passe",savePassword:"Enregistrer",passwordSaved:"Votre mot de passe a été mis à jour.",passwordTooShort:"Utilisez au moins 12 caractères.",resetLinkInvalid:"Ce lien est invalide ou expiré. Demandez-en un nouveau.",passwordUpdateFailed:"Le mot de passe n’a pas pu être mis à jour. Réessayez.",logout:"Déconnexion"}, nav:{overview:"Aperçu",assessments:"Évaluations",properties:"Propriétés",subscriptions:"Abonnements",invoices:"Factures",payments:"Paiements",profile:"Profil",support:"Assistance"}, dashboard:{...en.dashboard,title:"Mon compte",welcome:"Bienvenue",accountStatus:"Statut du compte",property:"Propriété",subscription:"Abonnement",nextPayment:"Prochain paiement",balance:"Solde dû",latestInvoice:"Dernière facture",upcomingService:"Prochain service",activity:"Activité récente",empty:"Aucune donnée pour le moment.",download:"Télécharger",reference:"Référence",submitted:"Soumis",status:"Statut",address:"Adresse",frequency:"Fréquence",amount:"Montant",date:"Date",due:"Échéance",paid:"Payé",contactSupport:"Contacter l’assistance"} },
  ar: { auth:{login:"تسجيل الدخول",email:"البريد الإلكتروني",password:"كلمة المرور",forgot:"نسيت كلمة المرور؟",signIn:"دخول",signingIn:"جارٍ الدخول…",invalid:"البريد الإلكتروني أو كلمة المرور غير صحيحة.",resetTitle:"إعادة تعيين كلمة المرور",resetIntro:"أدخل بريدك لإرسال تعليمات آمنة.",sendReset:"إرسال رابط الاستعادة",resetSent:"إذا كان الحساب موجودًا فقد أُرسلت التعليمات.",newPassword:"كلمة مرور جديدة",savePassword:"حفظ كلمة المرور",passwordSaved:"تم تحديث كلمة المرور.",passwordTooShort:"استخدم 12 حرفًا على الأقل.",resetLinkInvalid:"رابط إعادة التعيين غير صالح أو منتهي. اطلب رابطًا جديدًا.",passwordUpdateFailed:"تعذر تحديث كلمة المرور. حاول مرة أخرى.",logout:"تسجيل الخروج"}, nav:{overview:"نظرة عامة",assessments:"التقييمات",properties:"العقارات",subscriptions:"الاشتراكات",invoices:"الفواتير",payments:"المدفوعات",profile:"الملف الشخصي",support:"الدعم"}, dashboard:{...en.dashboard,title:"حسابي",welcome:"مرحبًا بعودتك",accountStatus:"حالة الحساب",property:"العقار",subscription:"الاشتراك",nextPayment:"الدفعة التالية",balance:"الرصيد المستحق",latestInvoice:"أحدث فاتورة",upcomingService:"الخدمة القادمة",activity:"النشاط الأخير",empty:"لا توجد بيانات بعد.",download:"تنزيل",reference:"المرجع",submitted:"تاريخ التقديم",status:"الحالة",address:"العنوان",frequency:"التكرار",amount:"المبلغ",date:"التاريخ",due:"الاستحقاق",paid:"مدفوع",contactSupport:"اتصل بالدعم"} },
  es: { auth:{login:"Iniciar sesión",email:"Correo electrónico",password:"Contraseña",forgot:"¿Olvidó la contraseña?",signIn:"Entrar",signingIn:"Iniciando sesión…",invalid:"El correo o la contraseña son incorrectos.",resetTitle:"Restablecer contraseña",resetIntro:"Introduzca su correo para recibir instrucciones seguras.",sendReset:"Enviar enlace",resetSent:"Si la cuenta existe, se han enviado instrucciones.",newPassword:"Nueva contraseña",savePassword:"Guardar contraseña",passwordSaved:"Su contraseña se ha actualizado.",passwordTooShort:"Utilice al menos 12 caracteres.",resetLinkInvalid:"Este enlace no es válido o ha caducado. Solicite uno nuevo.",passwordUpdateFailed:"No se pudo actualizar la contraseña. Inténtelo de nuevo.",logout:"Cerrar sesión"}, nav:{overview:"Resumen",assessments:"Evaluaciones",properties:"Propiedades",subscriptions:"Suscripciones",invoices:"Facturas",payments:"Pagos",profile:"Perfil",support:"Soporte"}, dashboard:{...en.dashboard,title:"Mi cuenta",welcome:"Bienvenido de nuevo",accountStatus:"Estado de la cuenta",property:"Propiedad",subscription:"Suscripción",nextPayment:"Próximo pago",balance:"Saldo pendiente",latestInvoice:"Última factura",upcomingService:"Próximo servicio",activity:"Actividad reciente",empty:"Aún no hay datos.",download:"Descargar",reference:"Referencia",submitted:"Enviado",status:"Estado",address:"Dirección",frequency:"Frecuencia",amount:"Importe",date:"Fecha",due:"Vence",paid:"Pagado",contactSupport:"Contactar soporte"} },
  de: { auth:{login:"Anmelden",email:"E-Mail-Adresse",password:"Passwort",forgot:"Passwort vergessen?",signIn:"Anmelden",signingIn:"Anmeldung…",invalid:"E-Mail oder Passwort ist falsch.",resetTitle:"Passwort zurücksetzen",resetIntro:"Geben Sie Ihre E-Mail für sichere Anweisungen ein.",sendReset:"Link senden",resetSent:"Falls das Konto existiert, wurden Anweisungen gesendet.",newPassword:"Neues Passwort",savePassword:"Passwort speichern",passwordSaved:"Ihr Passwort wurde aktualisiert.",passwordTooShort:"Verwenden Sie mindestens 12 Zeichen.",resetLinkInvalid:"Dieser Link ist ungültig oder abgelaufen. Fordern Sie einen neuen an.",passwordUpdateFailed:"Das Passwort konnte nicht aktualisiert werden. Versuchen Sie es erneut.",logout:"Abmelden"}, nav:{overview:"Übersicht",assessments:"Bewertungen",properties:"Immobilien",subscriptions:"Abonnements",invoices:"Rechnungen",payments:"Zahlungen",profile:"Profil",support:"Support"}, dashboard:{...en.dashboard,title:"Mein Konto",welcome:"Willkommen zurück",accountStatus:"Kontostatus",property:"Immobilie",subscription:"Abonnement",nextPayment:"Nächste Zahlung",balance:"Offener Betrag",latestInvoice:"Letzte Rechnung",upcomingService:"Nächster Service",activity:"Letzte Aktivitäten",empty:"Noch keine Daten.",download:"Herunterladen",reference:"Referenz",submitted:"Eingereicht",status:"Status",address:"Adresse",frequency:"Häufigkeit",amount:"Betrag",date:"Datum",due:"Fällig",paid:"Bezahlt",contactSupport:"Support kontaktieren"} },
  pt: { auth:{login:"Iniciar sessão",email:"E-mail",password:"Palavra-passe",forgot:"Esqueceu a palavra-passe?",signIn:"Entrar",signingIn:"A iniciar…",invalid:"O e-mail ou a palavra-passe está incorreto.",resetTitle:"Repor palavra-passe",resetIntro:"Introduza o e-mail para receber instruções seguras.",sendReset:"Enviar ligação",resetSent:"Se a conta existir, as instruções foram enviadas.",newPassword:"Nova palavra-passe",savePassword:"Guardar palavra-passe",passwordSaved:"A palavra-passe foi atualizada.",passwordTooShort:"Utilize pelo menos 12 caracteres.",resetLinkInvalid:"Esta ligação é inválida ou expirou. Solicite uma nova.",passwordUpdateFailed:"Não foi possível atualizar a palavra-passe. Tente novamente.",logout:"Terminar sessão"}, nav:{overview:"Resumo",assessments:"Avaliações",properties:"Propriedades",subscriptions:"Subscrições",invoices:"Faturas",payments:"Pagamentos",profile:"Perfil",support:"Apoio"}, dashboard:{...en.dashboard,title:"A minha conta",welcome:"Bem-vindo de volta",accountStatus:"Estado da conta",property:"Propriedade",subscription:"Subscrição",nextPayment:"Próximo pagamento",balance:"Saldo pendente",latestInvoice:"Última fatura",upcomingService:"Próximo serviço",activity:"Atividade recente",empty:"Ainda não existem dados.",download:"Transferir",reference:"Referência",submitted:"Enviado",status:"Estado",address:"Morada",frequency:"Frequência",amount:"Montante",date:"Data",due:"Vencimento",paid:"Pago",contactSupport:"Contactar apoio"} },
};

Object.assign(portalCopy.nl.dashboard, { access:"Toegang",services:"Diensten",acceptProposal:"Voorstel accepteren en doorgaan naar beveiligde betaling",save:"Opslaan",saved:"Opgeslagen",subject:"Onderwerp",message:"Bericht" });
Object.assign(portalCopy.fr.dashboard, { access:"Accès",services:"Services",acceptProposal:"Accepter la proposition et passer au paiement sécurisé",save:"Enregistrer",saved:"Enregistré",subject:"Objet",message:"Message" });
Object.assign(portalCopy.ar.dashboard, { access:"الدخول",services:"الخدمات",acceptProposal:"قبول العرض والمتابعة إلى الدفع الآمن",save:"حفظ",saved:"تم الحفظ",subject:"الموضوع",message:"الرسالة" });
Object.assign(portalCopy.es.dashboard, { access:"Acceso",services:"Servicios",acceptProposal:"Aceptar la propuesta y continuar al pago seguro",save:"Guardar",saved:"Guardado",subject:"Asunto",message:"Mensaje" });
Object.assign(portalCopy.de.dashboard, { access:"Zugang",services:"Leistungen",acceptProposal:"Vorschlag annehmen und zur sicheren Zahlung weitergehen",save:"Speichern",saved:"Gespeichert",subject:"Betreff",message:"Nachricht" });
Object.assign(portalCopy.pt.dashboard, { access:"Acesso",services:"Serviços",acceptProposal:"Aceitar a proposta e continuar para o pagamento seguro",save:"Guardar",saved:"Guardado",subject:"Assunto",message:"Mensagem" });
