#!/usr/bin/env bash
#
# Generate /opt/projects/mautic/.env with fresh secrets.
#
# Idempotent: if .env already exists it is left completely untouched, so running
# this twice can never rotate the DB password out from under a running MariaDB
# (which would lock Mautic out of its own database).
#
# Secrets are generated ON the server and never printed to stdout — read them
# back with `sudo cat /opt/projects/mautic/.env` if you need them.
#
# Usage:  sudo ./bootstrap.sh [--mailer-dsn smtp://...]
set -euo pipefail

STACK_DIR="/opt/projects/mautic"
ENV_FILE="${STACK_DIR}/.env"

MAILER_DSN=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mailer-dsn) MAILER_DSN="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "must run as root (the .env is root-owned 0600)" >&2
  exit 1
fi

if [[ -f "${ENV_FILE}" ]]; then
  echo "${ENV_FILE} already exists — leaving it untouched."
  echo "To rotate secrets, follow README.md §Rotating secrets instead."
  exit 0
fi

mkdir -p "${STACK_DIR}"

# `openssl rand -hex` output is safe to drop into a .env unquoted and, unlike
# base64, cannot contain characters (/, +, =) that would break a URL-shaped DSN.
gen() { openssl rand -hex 32; }

# Until a Resend key is supplied, park the mailer on Symfony's null transport.
# Mautic then boots and queues mail cleanly instead of crash-looping on an
# unresolvable SMTP host — mail simply is not delivered until the DSN is set.
if [[ -z "${MAILER_DSN}" ]]; then
  MAILER_DSN="null://null"
  echo "WARNING: no --mailer-dsn given; mail transport set to null://null (no email will be delivered)."
fi

umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). DO NOT COMMIT.
MAUTIC_IMAGE_TAG=7.1.3-apache

MAUTIC_DB_DATABASE=mautic
MAUTIC_DB_USER=mautic
MAUTIC_DB_PASSWORD=$(gen)
MAUTIC_DB_ROOT_PASSWORD=$(gen)

MAUTIC_SITE_URL=https://marketing.saasolution.es
MAUTIC_SECRET_KEY=$(gen)

MAUTIC_MAILER_DSN=${MAILER_DSN}
# Quoted: the value contains a space. Compose tolerates it unquoted, but any
# shell script that sources this file would try to execute the second word.
MAUTIC_MAILER_FROM_NAME="Dar Tahara"
MAUTIC_MAILER_FROM_EMAIL=hello@dartahara.com
EOF

chown root:root "${ENV_FILE}"
chmod 0600 "${ENV_FILE}"

echo "Wrote ${ENV_FILE} (root:root 0600) with freshly generated secrets."
