import { PortalCard, StatusBadge } from "@/components/portal/portal-shell";
import { portalCopy } from "@/i18n/portal-copy";
import { requireAuth } from "@/lib/portal-auth";
import { getRequestLocale } from "@/lib/request-locale";
import { requireCustomerPortal } from "@/lib/feature-flags";
import { createClient } from "@/lib/supabase/server";
import { money, shortDate } from "@/lib/portal-format";

export default async function AccountPage(){await requireCustomerPortal();const context=await requireAuth();const locale=await getRequestLocale();const c=portalCopy[locale].dashboard;const db=await createClient();const customerId=context.customerId||"00000000-0000-0000-0000-000000000000";const [customer,property,subscription,invoice,activity]=await Promise.all([
db.from("customers").select("full_name,status").eq("id",customerId).maybeSingle(),db.from("properties").select("address_line1,city,service_schedule").eq("customer_id",customerId).limit(1).maybeSingle(),db.from("subscriptions").select("status,billed_price_cents,currency,current_period_end").eq("customer_id",customerId).order("created_at",{ascending:false}).limit(1).maybeSingle(),db.from("invoices").select("id,invoice_number,status,amount_due_cents,amount_paid_cents,currency,due_at,created_at").eq("customer_id",customerId).order("created_at",{ascending:false}).limit(1).maybeSingle(),db.from("customer_activity").select("id,public_summary,event_type,created_at").eq("customer_id",customerId).order("created_at",{ascending:false}).limit(6)
]);const sub=subscription.data;const inv=invoice.data;return <div><p className="text-sm text-muted-foreground">{c.welcome}</p><h1 className="mt-1 font-serif text-4xl">{customer.data?.full_name||c.title}</h1><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><PortalCard title={c.accountStatus}><StatusBadge value={customer.data?.status||context.customerStatus||"applicant"}/></PortalCard><PortalCard title={c.property}><p className="text-sm">{property.data?`${property.data.address_line1}, ${property.data.city}`:c.empty}</p></PortalCard><PortalCard title={c.subscription}>{sub?<><StatusBadge value={sub.status}/><p className="mt-3 text-sm">{money(sub.billed_price_cents,sub.currency,locale)}</p></>:<p className="text-sm text-muted-foreground">{c.empty}</p>}</PortalCard><PortalCard title={c.nextPayment}><p className="text-sm">{sub?shortDate(sub.current_period_end,locale):c.empty}</p></PortalCard><PortalCard title={c.latestInvoice}>{inv?<><StatusBadge value={inv.status}/><p className="mt-3 text-sm">{money(inv.amount_due_cents,inv.currency,locale)} · {shortDate(inv.created_at,locale)}</p></>:<p className="text-sm text-muted-foreground">{c.empty}</p>}</PortalCard><PortalCard title={c.balance}><p className="font-serif text-2xl">{inv?money(Math.max(0,inv.amount_due_cents-inv.amount_paid_cents),inv.currency,locale):money(0,"EUR",locale)}</p></PortalCard></div><div className="mt-5"><PortalCard title={c.activity}>{activity.data?.length?<ul className="divide-y divide-border">{activity.data.map(row=><li key={row.id} className="py-3 text-sm"><p>{row.public_summary||row.event_type.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-muted-foreground">{shortDate(row.created_at,locale)}</p></li>)}</ul>:<p className="text-sm text-muted-foreground">{c.empty}</p>}</PortalCard></div></div>}
